apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/voutilad/argocd-k3d-redpanda.git
    targetRevision: HEAD
    path: cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager