apiVersion: v1
kind: Namespace
metadata:
  name: redpanda

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/voutilad/argocd-k3d-redpanda.git
    targetRevision: HEAD
    path: console
  destination:
    server: https://kubernetes.default.svc
    namespace: redpanda
  syncPolicy:
    syncOptions:
      - Validate=false
      - PruneLast=true
    automated:
      prune: true
      selfHeal: false