---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/voutilad/argocd-k3d-redpanda.git
    targetRevision: cluster
    path: redpanda
  destination:
    server: https://kubernetes.default.svc
    namespace: redpanda
  syncPolicy:
    syncOptions:
      - Validate=false
      - PruneLast=true
    automated:
      prune: true
      selfHeal: false