image:
  repository: docker.redpanda.com/redpandadata/redpanda
  tag: v23.3.9
  pullPolicy: Always

resources:
  cpu:
    cores: 1
    overprovisioned: true
  memory:
    container:
      min: 2Gi
      max: 2Gi

tls:
  enabled: true

statefulset:
  budget:
    maxUnavailable: 1
  initContainers:
    setDataDirOwnership:
      enabled: true