---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redpanda-console
  labels:
    helm.sh/chart: console-0.7.24
    app.kubernetes.io/name: console
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/version: "v2.4.5"
    app.kubernetes.io/managed-by: Helm
    
data:
  config.yaml: |
    # from .Values.console.config
    connect: {}
    kafka:
      brokers:
      - redpanda-0.redpanda.redpanda.svc.cluster.local.:9093
      - redpanda-1.redpanda.redpanda.svc.cluster.local.:9093
      - redpanda-2.redpanda.redpanda.svc.cluster.local.:9093
      sasl:
        enabled: true
      schemaRegistry:
        enabled: true
        tls:
          enabled: true
        urls:
        - https://redpanda-0.redpanda.redpanda.svc.cluster.local.:8081
        - https://redpanda-1.redpanda.redpanda.svc.cluster.local.:8081
        - https://redpanda-2.redpanda.redpanda.svc.cluster.local.:8081
      tls:
        enabled: true
