---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redpanda-console
  labels:
    helm.sh/chart: console-0.7.24
    app.kubernetes.io/name: console
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/version: "v2.4.5"
    app.kubernetes.io/managed-by: Helm
