---
# This is the root CA certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redpanda-default-root-certificate
  namespace: "redpanda"
  labels:
    app.kubernetes.io/component: redpanda
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redpanda
    helm.sh/chart: redpanda-5.7.35
spec:
  duration: 43800h
  isCA: true
  commonName: redpanda-default-root-certificate
  secretName: redpanda-default-root-certificate
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: redpanda-default-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
# This is the root CA certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redpanda-external-root-certificate
  namespace: "redpanda"
  labels:
    app.kubernetes.io/component: redpanda
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redpanda
    helm.sh/chart: redpanda-5.7.35
spec:
  duration: 43800h
  isCA: true
  commonName: redpanda-external-root-certificate
  secretName: redpanda-external-root-certificate
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: redpanda-external-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
# The self-signed issuer is used to create the self-signed CA
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: redpanda-default-selfsigned-issuer
  namespace: "redpanda"
  labels:
    app.kubernetes.io/component: redpanda
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redpanda
    helm.sh/chart: redpanda-5.7.35
spec:
  selfSigned: {}
---
# This is the self-signed CA used to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: redpanda-default-root-issuer
  namespace: "redpanda"
  labels:
    app.kubernetes.io/component: redpanda
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redpanda
    helm.sh/chart: redpanda-5.7.35
spec:
  ca:
    secretName: redpanda-default-root-certificate
---
# The self-signed issuer is used to create the self-signed CA
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: redpanda-external-selfsigned-issuer
  namespace: "redpanda"
  labels:
    app.kubernetes.io/component: redpanda
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redpanda
    helm.sh/chart: redpanda-5.7.35
spec:
  selfSigned: {}
---
# This is the self-signed CA used to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: redpanda-external-root-issuer
  namespace: "redpanda"
  labels:
    app.kubernetes.io/component: redpanda
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redpanda
    helm.sh/chart: redpanda-5.7.35
spec:
  ca:
    secretName: redpanda-external-root-certificate
